const express=require('express'); const {read,write}=require('../db'); const {auth}=require('../middleware/auth');
const router=express.Router();
function shape(p,db,me){const u=db.users.find(x=>x.id===p.userId);return {...p,user:u?{id:u.id,name:u.name,avatar:u.avatar}:null,likes:db.likes.filter(l=>l.postId===p.id).length,liked:!!db.likes.find(l=>l.postId===p.id&&l.userId===me),comments:db.comments.filter(c=>c.postId===p.id).map(c=>({...c,user:(()=>{const x=db.users.find(u=>u.id===c.userId);return x?{id:x.id,name:x.name,avatar:x.avatar}:null})()}))};}
router.get('/',(req,res)=>{const db=read();const me=req.headers['x-user-id']||'';res.json(db.posts.slice().sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).map(p=>shape(p,db,me)));});
router.post('/',auth,(req,res)=>{const {content,image=''}=req.body;if(!content||!content.trim())return res.status(400).json({message:'Post content is required'});const db=read();const p={id:Date.now().toString(),userId:req.user.id,content:content.trim(),image:image.trim(),createdAt:new Date().toISOString()};db.posts.push(p);write(db);res.status(201).json(shape(p,db,req.user.id));});
router.delete('/:id',auth,(req,res)=>{const db=read();const p=db.posts.find(x=>x.id===req.params.id);if(!p)return res.status(404).json({message:'Post not found'});if(p.userId!==req.user.id)return res.status(403).json({message:'You can delete only your own post'});db.posts=db.posts.filter(x=>x.id!==p.id);db.comments=db.comments.filter(x=>x.postId!==p.id);db.likes=db.likes.filter(x=>x.postId!==p.id);write(db);res.json({message:'Post deleted'});});
router.post('/:id/like',auth,(req,res)=>{const db=read();if(!db.posts.some(p=>p.id===req.params.id))return res.status(404).json({message:'Post not found'});const i=db.likes.findIndex(l=>l.postId===req.params.id&&l.userId===req.user.id);if(i>=0)db.likes.splice(i,1);else db.likes.push({postId:req.params.id,userId:req.user.id});write(db);res.json({liked:i<0,likes:db.likes.filter(l=>l.postId===req.params.id).length});});
router.post('/:id/comments',auth,(req,res)=>{const {text}=req.body;const db=read();if(!db.posts.some(p=>p.id===req.params.id))return res.status(404).json({message:'Post not found'});if(!text||!text.trim())return res.status(400).json({message:'Comment cannot be empty'});const c={id:Date.now().toString(),postId:req.params.id,userId:req.user.id,text:text.trim(),createdAt:new Date().toISOString()};db.comments.push(c);write(db);res.status(201).json(c);});
module.exports=router;
